[tasks.dev]
command = "cargo"
args = ["watch", "-q", "-c", "-w", "src/", "-w", ".cargo/", "-x", "\"run\""]


[tasks.example]
command = "cargo"
args = [
    "watch",
    "-q",
    "-c",
    "-w",
    "examples/",
    "-x",
    "\"run --example quick_dev\"",
]
